### ISSUE TITLE
Multiple Resolutions

### ISSUE THREAD

**Issue by JimTheCactus** [JimTheCactus/RedditWallpaperWatcher#1]
It'd be nice if this thing could watch for multiple resolutions. We're already spending our resources polling, so might as well be able to watch for stuff for multiple sizes since I have multiple screens I need wallpapers for (desktop, cellphone, etc.)

```yaml
---
    max_downloads: 5
    update_interval: 600000

    subreddits:
        moescape:
            # Folder is optional here. The subreddit name will be assumed if it's not provided.
            folder: Moe
        WidescreenWallpaper:

    sizes:
        desktop:
            width: 3440
            height: 1440
            aspect_ratio_tolerance: 0.05
            # Folder is optional here. The size name will be assumed if it's not provided.
            folder: Nadeshiko
        note10:
            width: 1080
            height: 1920
            aspect_ratio_tolerance: 0.05
```

The folder structure would be `<size>/<subreddit>`. The configuration above would produce images in four folders;
* `Nadeshiko/Moe`
* `Nadeshiko/WidescreenWallpaper`
* `note10/Moe`
* `note10/WidescreenWallpaper`
